"""Add ondelete cascade to bookings room_id

Revision ID: 15c0cf05994d
Revises: 4825b44d4e70
Create Date: 2025-10-26 21:56:35.712659

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15c0cf05994d'
down_revision = '4825b44d4e70'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('bookings_room_id_fkey'), 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'rooms', ['room_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('bookings_room_id_fkey'), 'bookings', 'rooms', ['room_id'], ['id'])
    # ### end Alembic commands ###
