"""Add complete status to bookingstatus enum

Revision ID: 4b2cda76001f
Revises: 15c0cf05994d
Create Date: 2025-10-28 02:58:18.735673

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b2cda76001f'
down_revision = '15c0cf05994d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
