"""Add description, building, image_url to Room

Revision ID: 6059216012ed
Revises: 7c2264e5704f
Create Date: 2025-10-23 15:33:59.383090

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6059216012ed'
down_revision = '7c2264e5704f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rooms', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('rooms', sa.Column('location', sa.String(length=255), nullable=False))
    op.add_column('rooms', sa.Column('image_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rooms', 'image_url')
    op.drop_column('rooms', 'location')
    op.drop_column('rooms', 'description')
    # ### end Alembic commands ###
