"""Add column admin_id to database

Revision ID: 67dad7b10160
Revises: 4b2cda76001f
Create Date: 2025-10-28 04:03:06.834002

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67dad7b10160'
down_revision = '4b2cda76001f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('admin_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'bookings', 'users', ['admin_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.drop_column('bookings', 'admin_id')
    # ### end Alembic commands ###
