"""Add updated_by_admin_id to bookings

Revision ID: dcf1068bda30
Revises: 67dad7b10160
Create Date: 2025-10-28 05:01:02.729077

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcf1068bda30'
down_revision = '67dad7b10160'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('updated_by_admin_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('bookings_admin_id_fkey'), 'bookings', type_='foreignkey')
    op.create_foreign_key(None, 'bookings', 'users', ['updated_by_admin_id'], ['id'])
    op.drop_column('bookings', 'admin_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bookings', sa.Column('admin_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'bookings', type_='foreignkey')
    op.create_foreign_key(op.f('bookings_admin_id_fkey'), 'bookings', 'users', ['admin_id'], ['id'])
    op.drop_column('bookings', 'updated_by_admin_id')
    # ### end Alembic commands ###
